### PR TITLE
Rename API to Dank (Dk)

### PR DESCRIPTION
**Pull request by asiekierka**
Arguments for the change:
- It's a much better name than Tesla.
- Not used by RotaryCraft.
- Does not disrespect Nikola Tesla.
- "Darkhax: I love the name, but I really can't bring myself to do something like that X)" - so I made a PR for you!
- This name will instantly make everyone use the API.
- It's cool and dank and all
- [A lot of the community supports the change](https://github.com/Darkhax-Minecraft/Tesla/issues/4#issuecomment-217544584)

Arguments against the change:
- You can only put anything in here if you're against fun.

### CODE REVIEW

**Comment by loordgek** [comment]
i think this is better than making a 1000 names for it

**Comment by asiekierka** [comment]
(If you're not okay with Danks, Pepes is also an option.)

**Comment by ForsakenHarmony** [comment]
#memes

**Comment by nabijaczleweli** [comment]
2dank4me

**Comment by Soundtoxin** [comment]
This is a terrible idea. Memes have gone too far.

**Comment by BBoldt** [comment]
I want this just so I can refer to the energy as "Donkey Kongs", in the same way MJ used to be "Michael Jacksons".

**Comment by Prospector** [comment]
Or we could go with a symbol, @asiekierka likes symbols. How about 🕴/t (levitating man in business suit per tick)

**Comment by xbony2** [comment]
Serious comment to add for reasons of renaming- @darkhax , "Tesla" was the name of a mod that died a while back, with its own unfinished power system. It ended after a fairly dramatic conflict, so distancing away from it may be wise.

**Comment by iamgreaser** [comment]
Another advantage is if a mod ever provides electric trains powered with this API you could literally make Thomas The Dank Engine.

**Comment by nabijaczleweli** [comment]
@ProfessorProspector You mean MAN IN BUSINESS SUIT LEVITATING per tick

**Comment by adrwa** [comment]
This.. seems like a good idea

**Comment by Darkhax** [comment]
Unfortunately this PR is too dank. There have already been several reports of meme overdosing in relation to this PR. For everyone's safety I am closing this PR.

**Comment by asiekierka** [comment]
We shall not be silenced! The memes will prevail!

**Comment by adrwa** [comment]
#memes4life

**Comment by Prospector** [comment]
I think this sounds fair. Dankhax has enough dank already, and the dankness must be kept sacred. Overuse of dankage would be far too dank and it would make the dank pretty dankin boring

**Comment by adrwa** [comment]
Dankhax always needs more dank.. he feeds off the dank

**Comment by AKTheKnight** [comment]
He merely adopted the dank. I was born in it. Moulded by it. I didn't see anything non-dank until I was already a man

**Comment by adrwa** [comment]
You think you know the dank? I know the dank and you cannot handle the dank...

**Comment by ForsakenHarmony** [comment]
But seriously Tesla is not a good name

**Comment by Prospector** [comment]
It's too late now. Maybe on the day dark released it a name change would work, but too many mods use it and it's already pretty well-known in the community now. You're stuck with Tesla.

**Comment by iamgreaser** [comment]
By that logic, it's too late for Minecraft modding to move to 1.9 because everything is on 1.7.10.

I'd say you need to apply this fix now, rather than wait until it becomes a lot of work.

**Comment by Prospector** [comment]
No that's completely irrelevant. Tesla is an established energy API and it would make no sense to change it now. It's already going to be a lot of work, plus renaming it would require every modder using the Tesla API to change the path to the tesla maven, and it would generally fuck everything up. And there's no reason to, Tesla is a great name.

> apply this fix now

What fix? There is no fix to make. There's no problem with the name Tesla.

@darkhax I highly suggest locking this thread

**Comment by iamgreaser** [comment]
Minecraft 1.7.10 is an established Minecraft version and it would make no sense to change it now. It's already going to be a lot of work, plus upgrading from it would require every modder using the Forge API to change the package path to Forge, and it would generally fuck everything up.

And more modders use the Forge API than the proto-Dank API.

Checkmate, atheists.

**Comment by AKTheKnight** [comment]
At what point does Athiesm come into this?

**Comment by Prospector** [comment]
Ignore him

**Comment by asiekierka** [comment]
@ProfessorProspector Tesla is not a great name and we already gave countless reasons for it including magnets

**Comment by kolatra** [comment]
@AKTheKnight It's a meme.

**Comment by adrwa** [comment]
**Opinions Inbound**: I dont see a point changing it from tesla, i like tesla, its a good name for an energy API.. dank was a good meme but it would not have been a good name for an energy api. Changing the name now would mean everyone who used it would have to change it.. and there would be no backwards compatibility. If you seriously think it should be changed make an issue discussing it or on the IRC.

**Comment by asiekierka** [comment]
@TheCodedOne We've spent months discussing it and no consensus has been reached. One of the issues was already locked and so will this one.

**Comment by kolatra** [comment]
Personally I think it would be great if mods came together and embraced being dank with a dank API.

**Comment by Prospector** [comment]
Then make a danks api and make it better than Tesla. Maybe when 1.10 or 1.11 rolls around it would be a hit. But this project is Tesla.

**Comment by adrwa** [comment]
The dank api could be something else.. like i said before dank doesn't really suit being an energy api

**Comment by Darkhax** [comment]
A lot of people want this thread locked to prevent further pointless discussion. I don't mind leaving it open, however at this point the name is not going to change and others probably don't want to be receiving notifications. Tesla was meant to be a somewhat serious mod and while it is fun to entertain the idea of naming in Dank, that just won't do. I have no problem with another API using Dank though. 

Thanks to everyone who contributed to this discussion.

**Pull request closed without merging**
