### PR TITLE
Allow Powerbar rendering from Tesla API

### PR DESCRIPTION
**Pull request by adrwa**

### CODE REVIEW

**Comment by adrwa** [comment]
screenshot_9

**Comment by adrwa** [comment]
Allows for with background, or without background incase you have a different colour preference

**Comment by adrwa** [comment]
Changed the code to be alot cleaner and easier to use

**Comment by Darkhax** [comment]
Why was this closed?

**Comment by Prospector** [comment]
I think he might be working on a seperate lib with this stuff? not entirely sure

**Pull request closed without merging**
