### PR TITLE
Added a few translations

### PR DESCRIPTION
**Pull request by gizmocodes**
Added translations for:
- Germany (de_DE)
- Spanish (es_ES)
- Mexican Spanish (es_MX)
- French (fr_FR)
- Japanese (ja_JP)

NOTE: These were mostly translated via Google Translate. Yes, I'm partially lazy.

### CODE REVIEW

**Comment by shadowfacts** [comment]
You shouldn't translate things for a project using Google Translate, you can't actually verify if they are correct. You should only translate things for which you yourself know both languages.

**Comment by N9199** [comment]
I'm a spanish speaker, I'll check the spanish ones, I have a friend who knows Japanese so I'll ask him to check that one.

Edit: My friend just checked the Japanese translation, according to him it should be alright, and I checked the spanish ones & I saw no mistakes.

**Comment by gizmocodes** [comment]
Whoops.
I used translate for a lot of basic languages for other projects; guess that was a bad idea. The German one I might know someone who could help, not sure if I could get ahold of her though.

**Comment by Keridos** [comment]
The German one is mostly correct, just the title should be "Deutsche Übersetzungen für den Tesla Mod."

**Comment by gizmocodes** [comment]
Fixed. That was the one language I knew a little of. At least I was close!

**Comment by Darkhax** [comment]
Very nervous to merge this PR because of the google translate bit. Don't really trust its accuracy. Will do further review. 

Edit: Seems mostly good, although not sure if there is much point for them since they're all mostly the same. They're also all impacted by #31

**Comment by RogueLogix** [comment]
i can also confirm the Japanese translation as correct.

edit: if "Penta" is a typo "ペンタ" needs to be corrected to "ペタ."

**Comment by gizmocodes** [comment]
That commit now updated the languages to include the tooltips. Also, I manually went over every file and updated the translations using 4 translation sites (Except Simplified Chinese, that crashed BabelFish), so it should be more accurate (Still not as accurate as an actual translator, however)

Also, I was asked "If you just used online translators, why'd you even do this at all?" I did it because I wanted to open up Tesla to a wider range of users from other (Non-US) countries. I tried, OK?

**Comment by amesgen** [comment]
The German translation is _right_, as @Keridos pointed out, but "Presse" for "Press" sounds very akward (I prefer "Drücke"). Also, I suggest to use "Output" and "Input" instead of "Ausgabe" and "Eingang", as these anglicisms are common words in Germany, and describe their meaning more accurately than their correct, but clunky "German" analogues.

**Comment by Darkhax** [comment]
Okay, if there are no further complains, I will merge.

**Comment by gizmocodes** [comment]
^^ I have no idea why that commit message misspelled itself.
_Ninja'd_

**Pull request merged**
